##Yaml template 
---
language: java
addons:
    sonarcloud:
        organization: linampatino-github
        token:
            secure: CssZOcX+2IzDmjZBh3GvZHrRGaBm6vls3dt6br0xgOxptoBkmgSpVhpwFwWScJFADjmNb+HRrlpGDmV0bB4xV3PFQpL9njhlLXU/ckuCWzafQ5+W1V288998QcYobyqpV4H3G0fpLj3YqFdgEvcg+HvzWxWZgHHPgI57ELhjMEI2Ec3+aFRHjycljCUS8LJ1CRVrxmmfmvG8pKErH4t0g61rBM07GSsBDDjMMJZzSI9+I1kZGHibgAj/SpacR/+qbfV/fviw+TnO1RjNAH/ruQG2/9o+JYu5pZcTL1oupn8jNm4HGonKhDuYKvjCYojs5JX/e7kykuEz0l4WermoqXXs2Ms+TzUd6NBgF0yEBaCjmen2c9MGR3t6kiiYAYg4kWOaPb44kQwmgquFau1QIax6KuHd4ia41hZ0jbErkdKaUvsX6cUTSPywtonehCChQyx0P/LAkSO2+aqZvYKOEtORsm0zi0NKESOEhQcZ66Yh+4WSD2Qkbb5dxQZE4X56zzQYmF9wESqntFc/l/QNL4Ih7eOvD+E49DWLNuuMBR9PVV+Tv6FLNNRmYH77bPnz+AOD/WaB/IpgmovuTl2PSMg6nQ8ufvAHHfidzrSAaCt+V8F0KQeKDgntymo2nBQ3LdOtKFj7N4NkMKkxr/tKxI0JYQKGnP+GDcu4uQcETbI=
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
