##Yaml template 
---
language: java
addons:
    sonarcloud:
        organization: linampatino-github
        token:
            secure: VUeJGFJ3rbN4qvZg3so7p+POpc6MRZ7a8Vmj9mu0w+CiBTTrm8bNRsevHThDGPjWcIpJtkyhB9Mt68EzUUQtnyM2WAE+R2Xs20b/O1oHFqpNktreyq9yqe4JbVUDbm2bYnKN73ob3Aak3sq1oIAnWMH1pQdTsmupz2paU2bMMrnQAuflyXlPCkLlIRGdhkJgYzwveq139DXLHVCZKJkGTSW9BYzw+MBlzpZ1UWljRb2nFPuHRAkWHCPxzrq7FLsWgsmYxqmuVdzvKNyoxXh/5LxZIppRKYr8c+07t3Dt9RK+x+nyHVuNPcpgoTS9jHwbB3qehZ/2pgs7QjC9TR1Jd5TkX9TZS5JLpWu7OAh/2dEaVRqtCxELkuqS2f2ipaEuEc5YdNZNPkbiWeU9y/BS9daHrdG3IKZC3iCi/rkwxnMzi4M9yRYVii6poNY+r/ZqfPrVsOgBNKGC769Tn7pHQO35br63OOSPf7FLaVsXq0cWq5MKBZoZWvA5hLF7Ev8eth859CtLvZGvTuWMqJnyAOE5BpsWNBZvo+wNAmdYCYBnwSKnhAri4EctCY4MuMs1TyJa9plnLqhOwgM+MA6ULyOivIKTGWvvR3u3Rlnkbuf5kjWLrBx2mxg2sKX/lkiNVg2OIQmWJ25WXPxHet8d1DFPzAKXK4P4q8wbEC4ggYk=
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
