##Yaml template 
---
language: java

addons:
    sonarcloud:
        organization: "lmpatino"
        token:
            secure: eQu6/wszmGZaQIIDsvf7jkluePtzCpPT1q7N2BG8Sn5RCSP/tITSj9LtlQAkxvlrpDyv3NLsy0b8p1vlDjhSjI4Aw2XSVSfMJfpz5tGq2jylcJCPaJFRIIAxYLf5a4VU5ofKE6mzHSIuR25lxsfCOWMdkPDUC5CUsIX6Fglsm20opqkwsqSiK5sffUtoqIM5cElEGSKgJWsHKd3IgEjRxqI6wrte0F1u/BAtGZg/l3zGmM2rC8UU8OYcIxShLXTfrQpDlsmAGg+xuTh2xZJcT4fydvZ0TS2XmalHljLdciIsJgWjIvZcnD3BYhBJHgQ3pqcfMKF1P7cRxXGD4YiDlk55amuYKfx/r67fEy6A+/pLYwnSiYuAhTzWOsMseUxqDvdM/o9ocyls2NukqXvzHQytzILrygdzpZNlCWu4BzJW+ePUWPENswpwcQzqho/M/XLl6TkjygNFXEDwJn5zOP/J7VDWQX3M+kYSnHejF1jpGasP705xEuthF66hUqUqAuTpX7qccI/bnnWWQOcAdFuStUSnzmSXCAuYNKsNxNyGNOtz5UZN4eD6/kCGuEOAF4fWiFgUJkZB6jb+nfbERcQBu2OLudepM0WvvWKmSQhvEZRhI2PpDUAZRBQCa0QXXd7AQYtP1bzkeunlO2D4dTBiopFKIKvNLVwl889QIfU=
    script:
       - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar